# Generated by Django 3.1.7 on 2021-03-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='carpet_area',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='quantity',
        ),
    ]
