# Generated by Django 3.1.7 on 2021-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210323_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='carpet_area',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
