# Generated by Django 3.1.7 on 2021-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210325_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='carpet_colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='carpet_area',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
