# Generated by Django 3.1.7 on 2021-03-29 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20210329_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='carpet_colour',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='carpet_length',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='carpet_width',
        ),
    ]
