# Generated by Django 3.1.7 on 2021-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_colour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='in_stock',
            options={'verbose_name_plural': 'In Stock'},
        ),
    ]
