# Generated by Django 3.1.7 on 2021-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='product',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
