# Generated by Django 3.1.7 on 2021-03-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_colour_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
