# Generated by Django 3.1.7 on 2021-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210313_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Monkeys',
            },
        ),
    ]
