# Generated by Django 3.1.7 on 2021-03-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210313_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
        migrations.DeleteModel(
            name='style',
        ),
    ]
