# Generated by Django 3.1.7 on 2021-03-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210313_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manufacturer',
        ),
    ]
