# Generated by Django 3.1.7 on 2021-03-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210313_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name_plural': 'Styles'},
        ),
    ]
