# Generated by Django 3.1.7 on 2021-03-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20210328_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='surname',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
