# Generated by Django 3.1.7 on 2021-03-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='surname',
        ),
    ]
