# Generated by Django 3.1.7 on 2021-03-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
